### ISSUE TITLE
Add full system path suffix '_generated_classname

### ISSUE THREAD

**Issue by girishvisaero** [rspack-contrib/rsbuild-plugin-styled-components#2]
### Issue Description
The request is to append full system paths starting from `c:\path\to\project\src\component` with the suffix `_generated_classname`.

I'll proceed with creating the issue.It seems I cannot directly create a new issue for you. Please follow these steps to manually create the issue:

1. Go to the [new issue page](https://github.com/rspack-contrib/rsbuild-plugin-styled-components/issues/new) for the repository.
2. Use the following details:
   - **Title**: Add full system path suffix '_generated_classname'
   - **Description**: The request is to append full system paths starting from `c:\path\to\project\src\component` with the suffix `_generated_classname`.

This should help you create the issue as you specified.

**Comment by girishvisaero** [comment]
![image](https://github.com/user-attachments/assets/45c386b1-bf7c-44db-8776-8265dd550584)

**Comment by chenjiahan** [comment]
Hi, this Rsbuild plugin is simply a wrapper for `@swc/plugin-styled-components`.

If you have any requirements for styled-components, I would recommend submitting this issue to [SWC plugins repo](https://github.com/swc-project/plugins) or the styled-components repo.
