### ISSUE TITLE
When the namespace option is set, the styled components class does not add a namespace.

### ISSUE THREAD

**Issue by sSarahlei** [rspack-contrib/rsbuild-plugin-styled-components#8]
When configuring the plugin in my rsbuild.config.js using the namespace option as follows: 
` plugins: [pluginStyledComponents({namespace:"my-namespace"})]`
The styled components class does not appear to have any namespaces added.
(The namespace was inserted appropriately when I used babel-plugin-styled-components in another webpack-based application.)

**Comment by chenjiahan** [comment]
Hi, this Rsbuild plugin is simply a wrapper for `@swc/plugin-styled-components`.

If you have any requirements for styled-components, I would recommend submitting this issue to [SWC plugins repo](https://github.com/swc-project/plugins) or the styled-components repo.
